<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Member extends \App\Entity\Member implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'artwork_type' => [parent::class, 'artwork_type', null],
        "\0".parent::class."\0".'birth_at' => [parent::class, 'birth_at', null],
        "\0".parent::class."\0".'contact_network' => [parent::class, 'contact_network', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null],
        "\0".parent::class."\0".'genres' => [parent::class, 'genres', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'interests' => [parent::class, 'interests', null],
        "\0".parent::class."\0".'isVerified' => [parent::class, 'isVerified', null],
        "\0".parent::class."\0".'is_published' => [parent::class, 'is_published', null],
        "\0".parent::class."\0".'is_self_published' => [parent::class, 'is_self_published', null],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null],
        "\0".parent::class."\0".'offers' => [parent::class, 'offers', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        'artwork_type' => [parent::class, 'artwork_type', null],
        'birth_at' => [parent::class, 'birth_at', null],
        'contact_network' => [parent::class, 'contact_network', null],
        'email' => [parent::class, 'email', null],
        'firstname' => [parent::class, 'firstname', null],
        'genres' => [parent::class, 'genres', null],
        'id' => [parent::class, 'id', null],
        'interests' => [parent::class, 'interests', null],
        'isVerified' => [parent::class, 'isVerified', null],
        'is_published' => [parent::class, 'is_published', null],
        'is_self_published' => [parent::class, 'is_self_published', null],
        'lastname' => [parent::class, 'lastname', null],
        'offers' => [parent::class, 'offers', null],
        'password' => [parent::class, 'password', null],
        'phone' => [parent::class, 'phone', null],
        'roles' => [parent::class, 'roles', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
