<?php

namespace ContainerEzAzC97;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JGNS_WfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JGNS.wf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JGNS.wf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Profile\\MyProfileController::edit' => ['privates', '.service_locator.n_LpSm1.App\\Controller\\Profile\\MyProfileController::edit()', 'getMyProfileControllereditService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.ojgjMmN.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController::verifUser' => ['privates', '.service_locator.Jk.A8Hx.App\\Controller\\RegistrationController::verifUser()', 'getRegistrationControllerverifUserService', true],
            'App\\Controller\\RegistrationController::resendVerif' => ['privates', '.service_locator.eR8LQuU.App\\Controller\\RegistrationController::resendVerif()', 'getRegistrationControllerresendVerifService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController::forgottenPassword' => ['privates', '.service_locator.eR8LQuU.App\\Controller\\SecurityController::forgottenPassword()', 'getSecurityControllerforgottenPasswordService', true],
            'App\\Controller\\SecurityController::resetPassword' => ['privates', '.service_locator..uQu1bZ.App\\Controller\\SecurityController::resetPassword()', 'getSecurityControllerresetPasswordService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Profile\\MyProfileController:edit' => ['privates', '.service_locator.n_LpSm1.App\\Controller\\Profile\\MyProfileController::edit()', 'getMyProfileControllereditService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.ojgjMmN.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController:verifUser' => ['privates', '.service_locator.Jk.A8Hx.App\\Controller\\RegistrationController::verifUser()', 'getRegistrationControllerverifUserService', true],
            'App\\Controller\\RegistrationController:resendVerif' => ['privates', '.service_locator.eR8LQuU.App\\Controller\\RegistrationController::resendVerif()', 'getRegistrationControllerresendVerifService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController:forgottenPassword' => ['privates', '.service_locator.eR8LQuU.App\\Controller\\SecurityController::forgottenPassword()', 'getSecurityControllerforgottenPasswordService', true],
            'App\\Controller\\SecurityController:resetPassword' => ['privates', '.service_locator..uQu1bZ.App\\Controller\\SecurityController::resetPassword()', 'getSecurityControllerresetPasswordService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Profile\\MyProfileController::edit' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifUser' => '?',
            'App\\Controller\\RegistrationController::resendVerif' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::forgottenPassword' => '?',
            'App\\Controller\\SecurityController::resetPassword' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Profile\\MyProfileController:edit' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifUser' => '?',
            'App\\Controller\\RegistrationController:resendVerif' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:forgottenPassword' => '?',
            'App\\Controller\\SecurityController:resetPassword' => '?',
        ]);
    }
}
