<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQT12Y9e\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQT12Y9e/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQT12Y9e.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQT12Y9e\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQT12Y9e\App_KernelDevDebugContainer([
    'container.build_hash' => 'QT12Y9e',
    'container.build_id' => '8ceaed63',
    'container.build_time' => 1743157508,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQT12Y9e');
