<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV0WwCEx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV0WwCEx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV0WwCEx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV0WwCEx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV0WwCEx\App_KernelDevDebugContainer([
    'container.build_hash' => 'V0WwCEx',
    'container.build_id' => 'ece299e5',
    'container.build_time' => 1741855713,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV0WwCEx');
